# sample monadic approach to read the outputs generated by freesurfer
c('tidyverse', 'furrr', 'ggseg') |> lapply(require, character.only = T)

# number of cores that could be allocated to the task for parallel processing
plan(multisession, workers = 12)
list(
    # list of atlases
  list("aparc.stats$", # for cortical desikan_killay
       "aparc.a2009s.stats$", # destrieux
       "aseg.stats$", # for subcortical desikan_killay
       "wmparc.stats$", # for white matter measures
       "aparc.pial.stats$" # for cortical pial measures
       ),
    # list of measures
  list("fs_cortical_measures_desikan_killay",
       "fs_cortical_measures_destrieux",
       "fs_subcortical_measures_desikan_killay",
       "fs_wm_measures",
       "fs_cortical_pial_measures"
       )
) |>
# parallel map
  future_pmap_dfr(~{
    # reading the measures for each 
    read_atlas_files("/path/to/the/freesurfer_output_top_level_folder", ..1) |>
    # converting to a long format
            pivot_longer(-c(subject, label), 
                         names_to = 'measure_name', 
                         values_to = 'measure_value') |> 
            mutate(measure_type = ..2)
    },
            .progress = T) |> 
    # writing the csv file
  write.csv('/path/to/fs_measures.csv'),
            row.names = F,
            quote = F)